#配置数据源
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/warehouse?useUnicode=true&characterEncoding=utf8&nullCatalogMeansCurrent=true&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true
      username: root
      password: 123456
      max-active: 20
      max-wait: 5000
      initial-size: 1
     #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      validationQuery: SELECT 'x'    #验证连接
      enable: true
   #监控配置
      stat-view-servlet:
        enabled: true
        login-username: root
        login-password: 123456
        allow:
        deny:
        url-pattern: /druid/*
  #thymeleaf的配置
  thymeleaf:
    cache: false
    enabled: true
#      web-stat-filter:
#        enabled: true
#        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  # activiti 工作流配置
  activiti:
    #建表规则   true： activiti会对数据库中所有表进行更新操作。如果表不存在，则自动创建。
    database-schema-update: true
    #检测历史表是否存在
    db-history-used: true
    #记录历史等级 可配置的历史级别
    history-level: full
    #关闭自动部署
    check-process-definitions: true


#配置mybatisplus
mybatis-plus:
  mapper-locations:
  - classpath:mapper/*/*Mapper.xml
  global-config:
    db-config:
    #主键类型 AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
       #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
       #field-strategy: NOT_EMPTY
    # mybatis-plus LOGO
    banner: false
  configuration:
      #控制台打印完整带参数SQL语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



#自定义的 shiro配置
shiro:
  #加密方式
  hash-algorithm-name: md5
  #散列次数
  hash-iterations: 2
  #放行的路径
  anon-urls:
  - /index.html*
  - /sys/toLogin*
  - /login/login*
  - /login/getCode
  - /resources/**
  #登陆地址
  login-url: /index.html
  #注销地址
  log-out-url: /login/logout*
  #拦截的路径
  authc-ulrs:
  - /**

#配置文件上传路径
filepath: E:/upload/

#打印 activiti 的sql日志
logging:
  level:
    org.activiti.engine.impl.persistence.entity: trace

